# Generated by Django 3.2.7 on 2021-09-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recibos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=70)),
                ('descricao', models.CharField(default='', max_length=200)),
                ('data', models.DateField()),
            ],
        ),
    ]
